### ISSUE TITLE
slit mapping problem

### ISSUE THREAD

**Issue by ChangQingScq** [ehkropf/SKPrime#100]
Does this repository support a ring map where the initial boundary is not circular? How do I get a slit mapping like S(a). Looking forward to your answer.
![image](https://github.com/ACCA-Imperial/SKPrime/assets/107191902/cf7f36e0-f09f-4feb-9e0d-cabf503d0ef8)

**Comment by ehkropf** [comment]
Best strategy would be to create a conformal map to a circle domain (each boundary maps to a circle) software exists for this, see e.g. Kropf and DeLillo's take on Fornberg's method, or you could just implement Fornberg's method). Once you have a circle domain, you can then use various methods (See DeLillo or DeLillo and Kropf (and sometimes Elcrat)).

Unfortunately I'm not sure anyone still maintains this. I'm working in a different field now and don't have time to play wiht this stuff any longer. Crowdy or Sheehan (see https://www.imperial.ac.uk/applied-computational-complex-analysis/acca-imperial/) might be a good resource for questions?
