### ISSUE TITLE
g0 evaluation error

### ISSUE THREAD

**Issue by rhodrin** [ehkropf/SKPrime#32]
In some domains at some boundary points greensC0 returns incorrect values. In the below code there is an error of 1 at two boundary points. In all cases in which I've seen errors, the error has always been 1 (but I'm not sure if that's true in general). May also apply to greensCJ.

``` matlab
dv = [
    -0.4-0.5i
    0.5+0.1i];
qv = [
    0.1
    0.15];

D = skpDomain(dv, qv);

zp = boundaryPts(D, 10);
alpha=0.2+0.0i;

g0 = greensC0(alpha, D);

gf=g0(zp);

w1 = skprime(alpha, D);
w2 = invParam(w1);

g0a = @(z) 1./(2i*pi).*log(w1(z)./(abs(alpha).*w2(z)));

ga=g0a(zp);

disp(ga-gf)
```

**Comment by ehkropf** [comment]
The discrepancy is due to the log branch. It's apparent if you look at the [phase plots of the two different versions](http://imgur.com/a/wb3kA). Alternatively, consider the comparison of the bits inside the log:

``` matlab
dv = [
    -0.4-0.5i
    0.5+0.1i];
qv = [
    0.1
    0.15];
D = skpDomain(dv, qv);
alpha=0.2+0.0i;
zp = boundaryPts(D, 10);

g0u = greensC0(alpha, D);
g0 = @(z) g0u(z) - real(g0u.hat(alpha));
eg0 = @(z) exp(2i*pi*g0(z));

w1 = skprime(alpha, D);
w2 = invParam(w1);
g0a = @(z) 1./(2i*pi).*log(w1(z)./w2(z)/abs(alpha));
eg0a = @(z) w1(z)./w2(z)/abs(alpha);

disp(eg0a(zp) - eg0(zp))
```

Closing as not actually a bug.
