### ISSUE TITLE
diff(g0) error

### ISSUE THREAD

**Issue by rhodrin** [ehkropf/SKPrime#39]
The function diff(g0) seems to now be giving erroneous results? (This wasn't previously the case).

In the below example, diff(g0) is the 'odd one out'.

``` matlab
dv = [
  0.052448+0.36539i
  -0.27972-0.12762i
   0.48252-0.28147i];
qv = [
  0.15197
  0.17955
  0.20956];
D = skpDomain(dv, qv);

alpha = 0.50842+0.54632i;
% alpha = 1./conj(alpha);

zin = -0.36035+0.32187i;

%%
% v1

w = skprime(alpha, D);
dw = diff(w);

wi = skprime(1./conj(alpha), D);
dwi = diff(wi);

dg0a = 1./(2i.*pi).*(dw(zin)./w(zin)-dwi(zin)./wi(zin)); 

disp(dg0a)

%%
% v2

g0 = greensC0(alpha, D);

dg0 = diff(g0);

disp(dg0(zin));

%% 
% v3

h = 1e-6;

g0a = @(z) 1./(2i*pi)*log(w(z)./(abs(alpha).*wi(z)));

disp((g0a(zin+h)-g0a(zin))/h)
```

**Comment by ehkropf** [comment]
I'll come back to this after #40.

**Comment by rhodrin** [comment]
Simple mistake causing this bug. The line

``` matlab
dval = dval + (1./(z - alpha) - 1./(z - conj(alpha)))/(2i*pi);
```

just needs to be switched with

``` matlab
dval = dval + (1./(z - alpha) - 1./(z - 1./conj(alpha)))/(2i*pi);
```

**Comment by rhodrin** [comment]
in greensC0.m of course.

**Comment by ehkropf** [comment]
If you make a pull request with this change, I'll merge it. I'm still working on the fallout from fixing #42.

**Comment by rhodrin** [comment]
I'm not sure what you mean by that sorry.

**Comment by ehkropf** [comment]
No worries. [Here's what is meant.](https://help.github.com/articles/using-pull-requests/) But honestly this is next on the list as soon as I'm done with the current issue.

**Comment by rhodrin** [comment]
Ta. Will have that done in a couple of mins.

**Comment by ehkropf** [comment]
Fixed with merge.
