### ISSUE TITLE
Second parameter derivative of G0 needs normalisation

### ISSUE THREAD

**Issue by ehkropf** [ehkropf/SKPrime#49]
See title.

**Comment by rhodrin** [comment]
Have a fix ready for this now but we'll need the 2nd derivative of the Greens function w.r.t. the variable in place to implement it.

**Comment by ehkropf** [comment]
Ok, #50 created.

**Comment by rhodrin** [comment]
Ok, got it. We're going to need diffp(w.hat,1) for this, i.e. d^2 \hat{G}_0/dzda.

So that brings up another issue. How do we want to fit 'hat' derivatives into the whole mixed derivative thing?
