### ISSUE TITLE
Implement higher order prime variable derivatives

### ISSUE THREAD

**Issue by ehkropf** [ehkropf/SKPrime#50]
How about this: Let the derivative function signature be `diff(w, n)` where `w` is the prime object and `n` is the order of the derivative. In other words, can we get away with a recursive implementation of this?

**Comment by rhodrin** [comment]
Sounds good, but how about mixed derivatives? dwp = diffp(w) then diff(dwp, n)?

**Comment by ehkropf** [comment]
Duplicate of #34.
